version: "3.8"

services:
  database:
    image: postgres
    container_name: voyage_canada_database
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: voyage_canada
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  frontend:
    build: ./frontend
    container_name: voyage_canada_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules

  backend:
    build: ./backend
    container_name: voyage_canada_backend
    depends_on:
      - database
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/app
      - /app/node_modules
