version: "3.8"

services:
  # frontend:
  #   stdin_open: true
  #   environment:
  #     - CHOKIDAR_USEPOLLING=true
  #   build:
  #     dockerfile: Dockerfile
  #     context: ./frontend
  #   volumes:
  #     - /app/node_modules
  #     - ./frontend:/app

  backend:
    build: ./backend
    container_name: voyage_canada_backend
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/app
      - /app/node_modules

  # nginx:
  #   depends_on:
  #     - frontend
  #     - backend
  #   restart: always
  #   build:
  #     dockerfile: Dockerfile
  #     context: ./nginx
  #   ports:
  #     - "80:80"
